services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hackamail-dev
    env_file:
      - ./backend/slack.env

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackamail-dev

  adminer:
  # Adminer is a database management tool that allows you to manage databases, tables, columns, relations, indexes, users, permissions, and more. Use it for debugging or just poking around. dont deploy in production
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db