FROM python:3.7

# Set the working directory in the container

WORKDIR /app

# Copy the dependencies file to the working directory

COPY requirements.txt .

# Install any dependencies

RUN pip install -r requirements.txt

# Copy the content of the local src directory to the working directory

COPY . .

# Command to run on container start

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]